from rest_framework import serializers

from .models import User

class UserSerializer(serializers.ModelSerializer):
    """
    Serializer for the User model.
    """
    class Meta:
        model = User
        fields = ['id', 'name', 'email', 'friends_count']
        read_only_fields = ['id']  # id is read-only, as it is auto-generated by Django

class FriendshipRequestSerializer(serializers.ModelSerializer):
    """
    Serializer for the FriendshipRequest model.
    """
    created_by = UserSerializer(read_only=True)
    class Meta:
        model = User
        fields = ['id',  'created_by']
        # read_only_fields = ['id', 'created_at']  # id and created_at are read-only, as they are auto-generated by Django