from rest_framework import serializers

from .models import User

class UserSerializer(serializers.ModelSerializer):
    """
    Serializer for the User model.
    """
    class Meta:
        model = User
        fields = ['id', 'name', 'email']
        read_only_fields = ['id']  # id is read-only, as it is auto-generated by Django